In [1]:
%load_ext autoreload
%autoreload 2

In [14]:
from isadream.nmr_demo_sa import *

In [46]:
# Build the complete ISA Investigation file.
invest = build_nmr_output()

In [47]:
# Search and return a list of matching studies.
matching_studies = get_studies_by_design_descriptor(invest, al_27_nmr)

In [58]:
df_list = list()

for study in matching_studies:
    # For each matching study, get its identifier.
    study_ID = study.identifier
#     print(study_ID)
    # Get each matching assay within the found studies.
    matching_assays = get_assays_by_measurement_type(study, ppm)
    # For each of these assays, get the associated DataFile and:
    for assay in matching_assays:
        # Get the Assay identifier.
        assay_ID = assay.identifier
#         print(assay_ID)

        # Get the sample from each assay. There could be more than one of these...
#         samples = assay.samples
        
        # For each data_file object.
        for data_file in assay.data_files:
            # Build the pandas dataframe:
            new_df = build_pandas_dataframe(data_file, 'isadream/demo_data')
            
            # Add the appropriate tags to the newly minted dataframe.
            new_df['assay_ID'] = assay_ID
            new_df['study_ID'] = study_ID
            
            # For each of the factor values appended to a sample, add the factor
            # name and value to the dataframe.
            for sample in assay.samples:
                for factor in sample.factor_values:
                    # Combine the name and unit for now.
                    new_df[str(factor.factor_name)] = factor.value
                
            
            # Append the new dataframe to the output list.
            df_list.append(new_df)

In [59]:
# Concatentate all these dataframes (which should already have matching
# columns...)
pd.concat(df_list, ignore_index=True)

,molarity hydroxide,ppm aluminum,assay_ID,study_ID,StudyFactor( name=Aluminate Molarity factor_type=Molarity comments=0 Comment objects )OntologyAnnotation( term=Molarity term_source=Extrinsic Material Property term_accession= comments=0 Comment objects )
0,0.89,79.96,sipos_2006_talanta_fig_3_KOH,sipos2006_talanta,0.005
1,2.93,79.90,sipos_2006_talanta_fig_3_KOH,sipos2006_talanta,0.005
2,4.92,79.84,sipos_2006_talanta_fig_3_KOH,sipos2006_talanta,0.005
3,6.85,79.72,sipos_2006_talanta_fig_3_KOH,sipos2006_talanta,0.005
4,9.13,79.66,sipos_2006_talanta_fig_3_KOH,sipos2006_talanta,0.005
5,10.71,79.66,sipos_2006_talanta_fig_3_KOH,sipos2006_talanta,0.005
6,2.93,79.82,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
7,4.98,79.54,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
8,0.93,79.98,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
9,6.97,79.13,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
10,8.96,78.45,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
11,10.95,77.67,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
12,12.99,76.47,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
13,14.92,74.53,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
14,16.97,73.14,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
15,18.92,71.32,sipos_2006_talanta_fig_3_NaOH,sipos2006_talanta,0.005
16,0.14,79.96,sipos_2006_talanta_fig_3_LiOH,sipos2006_talanta,0.005
17,0.66,79.92,sipos_2006_talanta_fig_3_LiOH,sipos2006_talanta,0.005
18,1.10,79.84,sipos_2006_talanta_fig_3_LiOH,sipos2006_talanta,0.005
19,1.64,79.66,sipos_2006_talanta_fig_3_LiOH,sipos2006_talanta,0.005
20,2.14,79.54,sipos_2006_talanta_fig_3_LiOH,sipos2006_talanta,0.005
21,2.59,79.36,sipos_2006_talanta_fig_3_LiOH,sipos2006_talanta,0.005
22,3.11,79.13,sipos_2006_talanta_fig_3_LiOH,sipos2006_talanta,0.005
23,3.59,78.83,sipos_2006_talanta_fig_3_LiOH,sipos2006_talanta,0.005
24,4.11,78.47,sipos_2006_talanta_fig_3_LiOH,sipos2006_talanta,0.005
25,4.00,79.22,sipos_2006_RSC_table1,sipos2006_RSC,3.000
26,3.40,79.23,sipos_2006_RSC_table1,sipos2006_RSC,3.000
27,2.80,79.22,sipos_2006_RSC_table1,sipos2006_RSC,3.000
28,2.20,79.44,sipos_2006_RSC_table1,sipos2006_RSC,3.000
29,1.60,79.48,sipos_2006_RSC_table1,sipos2006_RSC,3.000